### ISSUE TITLE
Cursor gone on the macOS terminal

### ISSUE THREAD

**Issue by chiffon-rouge** [jorisvink/ce#3]
Testing ce I discovered that the cursor doesn't show on the macOS terminal, while xterm (on macOS) works as intended. I understand that this is more or less a personal project, not intended for a wider user base and this might not be a problem as long as it works for your chosen terminal emulator. I just wanted to give you a heads up that it might not be usable with every terminal.

<img width="602" alt="Bildschirmfoto 2021-03-03 um 12 23 55" src="https://user-images.githubusercontent.com/4173092/109799463-60ce6680-7c1c-11eb-8bba-968066e92e55.png">

**Comment by jorisvink** [comment]
Hi,

Yeah I noticed. I don't use terminal.app but this seems the cursor got stuck in the bottom right side of the screen.

Interestingly, it will jump to the command prompt if you hit : or / so it's probably something silly regarding the terminal escape sequences being put out by ce.

**Comment by jorisvink** [comment]
Yup, ce uses the ANSI CSI s and CSI u for saving / restoring the cursor which I don't think terminal.app supports.

I should really use the vt100 ones (ESC 7 and ESC 8).

**Comment by jorisvink** [comment]
And now it'll work https://github.com/jorisvink/ce/commit/06d2a38aefb2c6a0bedaa793c3083f612d27898e

Thanks for the heads up!

**Comment by chiffon-rouge** [comment]
<img width="558" alt="Bildschirmfoto 2021-03-03 um 13 44 38" src="https://user-images.githubusercontent.com/4173092/109807880-c0ca0a80-7c26-11eb-8aff-fdc85ecda117.png">
